// demos/sample.vue
<script setup lang="ts">
import { computed, ref } from "vue";

const active = ref("ember");
const swatches = {
  ember: "#ff7a18",
  citrus: "#ffbc42",
  peach: "#ffd9a8"
} as const;

const activeColor = computed(() => swatches[active.value as keyof typeof swatches]);
</script>

<template>
  <section class="palette-preview">
    <h2>All Orange</h2>
    <button type="button" @click="active = 'citrus'">Citrus</button>
    <output>{{ activeColor }}</output>
  </section>
</template>

<style scoped>
.palette-preview {
  border-color: v-bind(activeColor);
  background: #160804;
  color: #ffd9a8;
}
</style>

// demos/sample.tsx
import { useMemo, useState } from "react";

type Swatch = {
  name: string;
  value: `#${string}`;
  locked?: boolean;
};

const initialSwatches: Swatch[] = [
  { name: "Ember", value: "#ff7a18", locked: true },
  { name: "Citrus", value: "#ffbc42" },
  { name: "Peach", value: "#ffd9a8" }
];

export function PalettePanel() {
  const [selected, setSelected] = useState(initialSwatches[0]);
  const cssVariables = useMemo(
    () => initialSwatches.map((swatch) => `--${swatch.name.toLowerCase()}: ${swatch.value};`),
    []
  );

  return (
    <section aria-label="Theme palette">
      <h2>{selected.name}</h2>
      <button type="button" onClick={() => setSelected(initialSwatches[1])}>
        Use citrus
      </button>
      <pre>{cssVariables.join("\n")}</pre>
    </section>
  );
}
